version: "3.9"
services: 
  web:
    build:
      context: ../.. 
      dockerfile: devops/stage/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env.stage
    environment:
      - NODE_ENV=staging
