version: "3.9"
services: 
  web:
    build:
      context: ../.. 
      dockerfile: devops/prod/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
