name: coodingrecipe
version: "3.9"
services: 
  coodingrecipe:
    container_name: recipe7
    build:
      context: ../.. 
      dockerfile: devops/local/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
