name: CI/CD Build and Deploy to ec2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run tests
        run: |
          npm install 
          npm run test:ci

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
              cd ${{ secrets.EC2_PROJECT_DIR }}
              git pull origin main
              docker compose -f devops/prod/docker-compose.yml up --build -d

          EOF
